### ISSUE TITLE
Support of latest Lucene version 8.6.x

### ISSUE THREAD

**Issue by kevindelord** [shashavali-d/android-lucene#1]
Hi there!

Good job on this repo!
My team and I are looking into a way to support the latest version of Lucene (8.6.x) on Android.

Could you explain us how did you port the version 8.4 to Android?
How did you do that? Any complication? Maybe you have a documentation somewhere?

Thanks in advance!!

kevin

**Comment by shashavali-d** [comment]
Porting is done using Java Reflections API, which you can find from the source package src/main/java/org.apache.lucene.mobile
You can put/copy this package inside any lucene version which will make it to work with Android. Below steps shall be useful:
1. Download the apache lucene from https://lucene.apache.org/ page
2. I used Gradle build tool with Intellij, I advice you to use the same and open the project.
3. Now, delete unncessary folders such as dev-tools and solr from the downloaded source. My interests are mainly for enabling searching/indexing which are part of lucene-core package, so, other packages such as benchmark, monitor, classifications, luke, test framework, tools, spatial etc. can be deleted. Similarly, folders "data", "test" and files build.xml, ivy.xml under each package shall also be deleted.
4. The lucene is built using Ant but I used gradle, so, add build.gradle and settings.gradle files in lucene. Close and reopen the project once gradle files are added.
5. And, now you would be prompted with "import changes", if so, select it, the project syncs and then in a while you may see gradlew, gradlew.bat files in your project.
6. The base code, copy "mobile" and place it inside downloaded lucene core package i.e., org.apache.lucene
7. Go to project structure, select modules and mark the src and resources as Sources and Resource sets repectively.
Before this create the empty folder called "resources" under src/main
8. Now, go to Terminal, from the project root directory, run ./gradlew build which generates *.jar inside libs folder of a project.
9. If you happened to get any compilation errors of a dependency module or package, then all those packages must be moved in to org.apache.lucene. Build must be successful once all the dependencies are resolved .

With the above steps you shall be able to get jar which you can use in your Android application as like anyother jar and use lucene for indexing and searching.

You can refer my repo https://github.com/shashavali-d/lucenestudy which uses lucene API inside Android application
